version: '3'
services:
  backend:
      build: 
            context: ./backend
      ports:
        - "5001:5000"
      volumes:
        - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend