version: '3'
services:
  backend:
      build: 
            context: ./todo_app_back
      ports:
        - "5001:5000"
      volumes:
        - ./todo_app_back:/app

  frontend:
    build:
      context: ./todo_app_front
    ports:
      - "3000:3000"
    volumes:
      - ./todo_app_front:/app
      - /app/node_modules
    depends_on:
      - backend